### ISSUE TITLE
Breadcrumb issues with long paths when editing a text file

### ISSUE THREAD

**Issue by mikeazo** [owncloud/files_texteditor#10]
### Steps to reproduce
1. Put a text file in a directory with a long path
2. Click on the text file to edit it

### Expected behavior
Since the path is so long, it cannot all fit in the breadcrumb. When not in the editor, a ... shows up in the breadcrumb. Expect that the ... would stay when in the editor.

### Actual behavior
The ... goes away and the whole path shows up in the breadcrumb. This pushes portions of the breadcrumb, the save and close buttons, and the search box down a line. See the attached screenshot.

In other apps like PDF Viewer and Picture Viewer, the breadcrumb disappears, so they are not affected. Which is why I put the bug in this app.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
6.0.1

**Updated from an older ownCloud or fresh install:**
fresh install

### Client configuration
**Browser:**
Latest Safari

**Operating system:**
Mac 10.9

![screen shot 2014-02-28 at 9 00 45 am](https://f.cloud.github.com/assets/6683518/2294384/e7b2a596-a080-11e3-9550-ba7743d98c78.png)
![screen shot 2014-02-28 at 9 01 26 am](https://f.cloud.github.com/assets/6683518/2294385/e7b641c4-a080-11e3-943e-6544113a3bf9.png)

**Comment by tomneedham** [comment]
No longer displays the breadcrumb in the latest version.
