### ISSUE TITLE
New version of files_texteditor freezes IE8

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#107]
### Steps to reproduce
Using internet explorer 8 open a textfile.

### Expected behaviour
File is opened.

### Actual behaviour
Browser gets frozen.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Internet explorer 8.0.7601

**Comment by davitol** [comment]
Same behaviour in IE9

**Comment by PVince81** [comment]
It's because Internet Explorer is cold :snowflake:

**Comment by tomneedham** [comment]
@SergioBertolinSG How did you install OC? From the daily builds? I've just done a clean instal from git master, same OS, IE8.0.6001 and it functions correctly so need to try and reproduce your setup.

**Comment by SergioBertolinSG** [comment]
Retested in a dfiferent environment (previous is windows server 2008).
Currently on windows 10 with emulations of several ie versions, ie9 and later works there. But ie8 keeps the spinner spinning when trying to open the file and the server is blocked waiting for the spinner to finish.

**Comment by PVince81** [comment]
With the lastest text editor master, also doesn't load in IE8

**Comment by tomneedham** [comment]
I've been using XP with IE8 installed and still have yet to reproduce this. Perhaps one of you two can checkout console? Does the official ace kitchen sink work for you: https://ace.c9.io/build/kitchen-sink.html and we could look at upgrading the ace version if its perhaps that which needs fixing

**Comment by SergioBertolinSG** [comment]
Closing this as we have ended support of IE8.
