### ISSUE TITLE
Several code files are not considered code.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#110]
They have a text icon instead the new code icon.

![screen shot 2015-09-21 at 13 08 26](https://cloud.githubusercontent.com/assets/9048796/9990469/e32a1516-6061-11e5-93e9-e8ccdc81b11c.png)

@jancborchardt

**Comment by jancborchardt** [comment]
@schiesbn can you fix that? Not sure what the mimetype is.

@SergioBertolinSG any other filetype mappings missing? Please list them here if there are any.

**Comment by SergioBertolinSG** [comment]
.xml and .tex have the same problem.

![screen shot 2015-09-22 at 08 56 11](https://cloud.githubusercontent.com/assets/9048796/10012388/deb0595e-6107-11e5-8d06-2b0a661a1a43.png)

.abap .ads .agi .algol .e .apl .scpt .arc. ArnoldC .as .au3 .awk .bas .bat .befunge .bg .boo .bf .ceylon .clj .cbl .coffee .cfml .lisp .context .cs .csh .d **.dart** .pas .djs .ecl .e .ex .lisp .erl .fal .f .fy .fan .fimpp .fs **.go** .golo .gsx .groovy .hs .hs .ho .hq9plus .idr .io **.java** .jl .kt .ls .lgt .lol .lua .m4 .mathematica .m .mod .nasm .n .ml .omgrofl .pn .ps1 .pde .pure .r .rkt .rexx .rb .sml .sbl **.sql** .stata .swift **.tcl** .uc .vala .v .vim .vb .asm .xpath2 .xquery .xslt .xtend .zu

I think bolded ones needs to be fixed specially since those filetypes are very used.

All this file types are code and are showed as undetected type, like .rtf which is not detected as a document.

![screen shot 2015-09-22 at 08 55 51](https://cloud.githubusercontent.com/assets/9048796/10012392/e942fcaa-6107-11e5-9780-9b88efc9424a.png)

**Comment by SergioBertolinSG** [comment]
Perhaps this is not the correct repo, I am moving this to core.

**Comment by SergioBertolinSG** [comment]
Opened in core: https://github.com/owncloud/core/issues/19254
