### ISSUE TITLE
Reload file list when closing editor

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#111]
### Steps

1. Open text file
1. Edit it
1. Close editr

### Expected result
File list reloads, preview icon appears / gets updated

### Actual result
File list doesn't reload, outdated/missing preview

@tomneedham 

Please trigger `fileList.reload()` for now.
Hopefully one day this will be wrapped by a proper API: https://github.com/owncloud/core/issues/13414

**Comment by PVince81** [comment]
By the way, this is a regression from pre-2.0

**Comment by tomneedham** [comment]
This was removed intentionally following discussion with @jancborchardt. The reload was ugly for the user experience and actually the regenerated review was not hugely useful for text files. If we want this back badly we should look at handling the reload in a nicer way (no temporary blank files list)

**Comment by jancborchardt** [comment]
Yeah, the reload is a hugely annoying experience. It’s much more important to have that smooth than to fix the preview icon.

**Comment by jancborchardt** [comment]
(If that is an either-or situation and we can’t have it both.)

**Comment by PVince81** [comment]
@tomneedham you can try this: https://github.com/owncloud/core/blob/master/apps/files_versions/js/versionstabview.js#L96

You can get the file model from the context: `context.fileInfoModel` (it's a backbone model, the file list listens for attribute changes, so changing them will rerender the row)

**Comment by PVince81** [comment]
the context being the one from the file action handler

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/files_texteditor/pull/115
However it's missing the size
