### ISSUE TITLE
An error should be shown trying to open a renamed file in another browser tab without refreshing

### ISSUE THREAD

**Issue by davitol** [owncloud/files_texteditor#114]
### Steps to reproduce
1. Open two browser tab with the same server
2. Tab1: Create a file
3. Tab2: Refresh the browser (new file created in step two appears)
4. Tab1: Rename the file
5. Tab2: Without refreshing, try to open the file.

### Expected behaviour
An error should be shown

### Actual behaviour
The text editor gets blank and spinning.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
{"reqId":"HN2jG3kGCRXw+\/4KPlxE","remoteAddr":"82.159.139.58","app":"files_versions","message":"-1 is not a valid value for maximal versions retention obligation. Check versions_retention_obligation in your config.php. Falling back to auto.","level":2,"time":"2015-09-24T10:35:00+00:00"}
{"reqId":"LzXIwGH+0yjmTrhFKfb4","remoteAddr":"82.159.139.58","app":"files_versions","message":"-1 is not a valid value for maximal versions retention obligation. Check versions_retention_obligation in your config.php. Falling back to auto.","level":2,"time":"2015-09-24T10:35:29+00:00"}
{"reqId":"Hcs\/B3pQEmmge7GWspSx","remoteAddr":"82.159.139.58","app":"PHP","message":"fopen(\/opt\/owncloud\/data\/admin\/files\/incidencia.txt): failed to open stream: No such file or directory at \/opt\/owncloud\/apps\/files_locking\/lib\/lock.php#93","level":3,"time":"2015-09-24T10:35:32+00:00"}
### Client configuration

**browser**
Firefox

Note: Behaviour in oc server 8.1.3 was the following

![screen shot 2015-09-24 at 12 28 31](https://cloud.githubusercontent.com/assets/10596560/10071335/6f82ebec-62b9-11e5-8924-837006b21ece.png)

**Comment by DeepDiver1975** [comment]
fixed with #117
