### ISSUE TITLE
Don't break common browser shortcuts

### ISSUE THREAD

**Issue by schiesbn** [owncloud/files_texteditor#118]
I just discovered that Ctrl+t doesn't open a new browser tab if I have the text editor open. Instead it mixes up the words in my document. I think that's a really bad behavior. People are used to hit Ctrl+t in their browser to open a new tab and they will do so without thinking about it, not even for a millisecond. I consider it a bad user experience if this will result in mixing up the words instead of performing the expected default action.

Having text editor specific shortcuts is great but they shouldn't change the behavior of well known browser short cuts.

Opinions?  @jancborchardt @nickvergessen @MorrisJobke @LukasReschke @tomneedham

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Fix is in #119
