### ISSUE TITLE
Bring back the "Save" button

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#122]
I miss it when testing version creation.

**Comment by tomneedham** [comment]
@jancborchardt How should we handle this? Right now it autosaves after 3 seconds of inactivity, and the keyboard shortcuts still trigger a manual save.

**Comment by jancborchardt** [comment]
@PVince81 Ctrl+S or just wait for the autosave. The target audience for the text editor are not developers trying to test ownCloud. ;)
