### ISSUE TITLE
Increase version for 9.0

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/files_texteditor#128]
Just a warning, when stable8.2 is branched off in core (most likely today), the app version should also be increased (first or second digit, to allow updates in stable8.2 later, in case it is needed).

Also the version file can be melted into the info.xml, e.g.:
```xml
<version>2.1</version>
```

**Comment by jancborchardt** [comment]
@nickvergessen @tomneedham is this solved? Btw @nickvergessen if you find stuff like this you can just sent a PR. ;)

**Comment by nickvergessen** [comment]
Sorry, wasn't interested to do 30 PRs yet again, since I did that for all apps...
---

No, still not addressed.
