### ISSUE TITLE
Closing the editor increments the file counter in the files list

### ISSUE THREAD

**Issue by tomneedham** [owncloud/files_texteditor#139]
### Steps to reproduce
1. Open a text file
2. Add some content and close it

### Expected behaviour
File counter remains the same

### Actual behaviour
File counter at the bottom of the files list increments

Using pre-9.0 master and text editor master

**Comment by tomneedham** [comment]
Offending line https://github.com/owncloud/files_texteditor/blob/master/js/editor.js#L536

**Comment by PVince81** [comment]
It's a bug in `updateRow()` in core: https://github.com/owncloud/core/issues/19709
