### ISSUE TITLE
js/aceeditor/worker-javascript.js is non free

### ISSUE THREAD

**Issue by DavidPrevot** [owncloud/files_texteditor#143]
As per https://github.com/owncloud/apps/issues/867, the `js/aceeditor/worker-*` files are not used by ownCloud, and `js/aceeditor/worker-javascript.js` is non free. Even if the license comments have been stripped away upstream, the code is still the same and part of it contain the terrible “The Software shall be used for Good, not Evil” clause.

https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript/jshint.js

**Comment by tomneedham** [comment]
@DavidPrevot Please see the fix here: https://github.com/owncloud/files_texteditor/pull/144
