### ISSUE TITLE
Add "Text file" to "+" menu, remove from core

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#147]
Currently, the "+" menu in core already contains the action "Text file".
However, creating a text file from the GUI doesn't make much sense if there is no text editor, because then it only means creating empty text files.

I suggest that we do the following:
1) Remove "Text file" from the menu in core https://github.com/owncloud/core/blob/v8.2.0/apps/files/js/newfilemenu.js#L201
2) Make the text editor app insert this element with this new API: https://doc.owncloud.org/server/9.0/developer_manual/app/js.html#extending-the-new-menu-in-the-files-app

Note that in 9.0 the public page will also contain this menu after https://github.com/owncloud/core/pull/16902 is merged, so the text editor should first check if we are in public mode before inserting the element, because the text editor doesn't work on the public page.

Bonus: after the file is created, automatically open the text editor. For that, use `this.createFile().then(function() {...})` from inside the plugin to run code after the file was created.

@tomneedham @jancborchardt

**Comment by nickvergessen** [comment]
Sounds like a neat idea. Hopefully the markdown plugin will make use of that as well :no_mouth:

**Comment by tomneedham** [comment]
I like this a lot :)

**Comment by PVince81** [comment]
I believe the markdown app requires the text editor app to be enabled, so shouldn't be an issue

**Comment by jancborchardt** [comment]
Yeah, good call! Creating a new folder should be second in the list anyway (after Upload). :)
