### ISSUE TITLE
Text file does not open in editor when using Favourites

### ISSUE THREAD

**Issue by johndevs** [owncloud/files_texteditor#152]
I have marked a text file as a favourite.

When I click the file under "All Files" the file opens in the text editor but when I open the file under Favourites the file is downloaded. I would expect the behaviour to be same under Favourites as it is under Files.

**Comment by tomneedham** [comment]
Please could you use the issue template so we have some idea of your environment: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by phil-davis** [comment]
It works for me in 10.0.3-beta2 and current files_texteditor:
1) Create some text file t.txt and type stuff in it.
2) Mark it as a favorite
3) Click and open the file to edit - works
4) Go to Favorites
5) Click and open the file to edit - works

I tried in a sub-folder etc also. Cannot find how it is broken. Please reopen and give more detail if you can reproduce this.
