### ISSUE TITLE
Selecting some text clicking and dragging and release click outside texteditor's view, closes the editor.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#158]
### Steps to reproduce

1. Upload a text file full of text.
2. Open the file.
3. Select some lines dragging the mouse while clicking.
4. Release the click out of the editor.

### Expected behaviour
Text keeps selected and editor open.

### Actual behaviour
Editor gets closed and the user frustrated.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**Comment by SergioBertolinSG** [comment]
@tomneedham This one is annoying.

**Comment by tomneedham** [comment]
Yeah tried to reproduce this afternoon. Which browser?

**Comment by SergioBertolinSG** [comment]
I've seen it on Chrome.
