### ISSUE TITLE
Make text editor work with sharing overview

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#17]
Currently the text editor can only work in the files app.

The following needs to be done:
1) Use OCA.Files.fileActions.register() instead of the deprecated FileActions.register()
2) Use the action's context variable to find out in which fileList to render the container/breadcrumb
3) Better encapsulation of the code, needs to support the existence of multiple file list DOM elements on the same page

**Comment by jancborchardt** [comment]
@tomneedham any update on this? This also breaks opening text files in the Favorites view.

**Comment by tomneedham** [comment]
Yes I shall take a look at this this week

**Comment by DeepDiver1975** [comment]
> This also breaks opening text files in the Favorites view.

not nice - but not critical as well -> 8.1

**Comment by PVince81** [comment]
Related: https://github.com/owncloud/files_texteditor/issues/37

**Comment by PVince81** [comment]
Already works in the 8.2 version / text editor 2.0
