### ISSUE TITLE
Is not possible to create text files with the same name of a folder.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#175]
### Steps to reproduce:

Having the folder Documents in the root folder do:
1. Create a text file called Documents.
### Expected behaviour:

Text file is created and folder is still there.
### Actual behaviour

It shows an error saying that "Documents" already exist.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.2","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

Observed also in stable9.

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```
### Client configuration

**browser**
Chrome

**Comment by nasli** [comment]
Same behavior when:
1-try to upload a file "Documents" 
2.Dialog to select keep new files or already existing files appears, select keep new one
3.Error uploading file. Upload failed. Could not find uploaded file.

**Comment by PVince81** [comment]
Is this a regression ?

**Comment by SergioBertolinSG** [comment]
> Is this a regression ?

No, even with old editor in stable8 it is happening also.

**Comment by PVince81** [comment]
Did you call it "Documents.txt" or did you manually remove the extension ?

**Comment by SergioBertolinSG** [comment]
Removed the extension manually. It has to be the same name as a folder.

**Comment by PVince81** [comment]
Well then it is normal that you can't create it as you can't have a directory entry that is both a file and a folder at the same time

**Comment by PVince81** [comment]
please don't tell me that Mac allows this 🙈

**Comment by SergioBertolinSG** [comment]
Ah, no, my mistake. In mac it lies to you a little when renaming in finder, you need to open properties of the file to properly remove the extension.
