### ISSUE TITLE
Text editor doesn't update the error and shows the previous one.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#176]
### Steps to reproduce:

Having the folder Documents in the root folder do:
1. Create a text file "New text file.txt".
2. Try to create again the same file.
3. Erase the name, write a dot.
### Expected behaviour:

An error tooltip appears saying that "." is not an allowed name.
### Actual behaviour

An error tooltip appears saying that "New text file.txt" already exists.
![screen shot 2016-05-23 at 10 13 41](https://cloud.githubusercontent.com/assets/9048796/15464420/874ea5d4-20cf-11e6-9688-d81e5beff103.png)
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.2","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

Observed also in stable9.

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```
### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment]
That's a bug in core where the logic about duplication is. It will probably happen also somehow with creating folders.

**Comment by PVince81** [comment]
It's a problem with the tooltip which doesn't re-render itself with the new contents. Needs a hack that removes + re-adds the tool tip.

**Comment by PVince81** [comment]
junior job -> 9.2

**Comment by phil-davis** [comment]
Fixed in core master https://github.com/owncloud/core/pull/27964
and in core stable10 https://github.com/owncloud/core/pull/28151
