### ISSUE TITLE
Preview thumbnail is not available creating a new text file

### ISSUE THREAD

**Issue by davitol** [owncloud/files_texteditor#178]
### Steps to reproduce:

Having the folder Documents in the root folder do:
1. Create a text file "file.txt" and edit it writing some text
2. Save the file in order to go back to the files view

### Expected behaviour:

A thumbnail preview with the text written should be shown.

### Actual behaviour

The thumbnail preview is not shown. 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** 

9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'supportedDatabases' =>
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
  ),
  'instanceid' => 'oc3wv0vyv831',
  'passwordsalt' => 'icyhFzjChsskoH28Gp+S9nwWT+exaf',
  'secret' => 'TTbE97IubBKXN53uoLSJ3tjvxGy0g8RJ3gIWH0ez9ltlHfWo',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'docker.oc.solidgear.es',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => 'http://docker.oc.solidgear.es',
  'dbtype' => 'mysql',
  'version' => '9.1.0.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'yABgoDZXWOz3PNuNE7axny8zECJU0l',
  'logtimezone' => 'UTC',
  'installed' => true,
  'license-key' => 'demo-20160625-80e046c4d642dfa0-a9a2295f',
  'enable_previews' => true,
  'preview_max_x' => 640,
  'preview_max_y' => 640,
  'enabledPreviewProviders' =>
    array (
      0 => 'OC\\Preview\\Movie',
      1 => 'OC\\Preview\\Image',
    ),
  'enable_movie_transcode' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

No logs are shown in owncloud.log

### Client configuration

**browser**
Firefox

**Comment by davitol** [comment]
The issue can be only reproduce if i add to the config.php file the following configuration:

```
  'enable_previews' => true,
  'preview_max_x' => 640,
  'preview_max_y' => 640,
  'enabledPreviewProviders' =>
    array (
      0 => 'OC\\Preview\\Movie',
      1 => 'OC\\Preview\\Image',
    ),
  'enable_movie_transcode' => true,
);
```

**Comment by PVince81** [comment]
Works for me on master. Note that you might need a certain minimum amount of characters for the preview to appear.
