### ISSUE TITLE
Text edit error: file is locked

### ISSUE THREAD

**Issue by fbennett** [owncloud/files_texteditor#223]
This is one of two failure scenarios we are seeing in our OC installation. The other is reported at #222. As noted in the other report, the OC version on the server is unclear. I will add that info here after confirming with our admins.

## Steps to reproduce
1. In the web view of a subdirectory, create a named text file with `+`:arrow_right:`New text file`.

## Expected
The file should open for editing.

## Result
2. Nothing further occurs.
3. Refreshing the display brings the file into the listing (and not prefixed with path clutter)
4. Clicking on the filename opens the editor
5. After typing text into the editor, the status line at the top reports saving, then "file is locked"
6. Closing the editor raises an error report at the top of the screen, with "Click to continue editing."
7. After refreshing the display, the file is still locked. Go to 6.
8. Meanwhile, the empty file syncs to the desktop client.
9. Deleting the file on the desktop and syncing succeeds in removing it from the web listing.
-----
When this failure occurs, the JS console shows a `400` failure against an ajax call that has `dir=WebCenterInfoGSL`, where the actual OC path to the file is `dir=/Web/CenterInfo/GSL`. Could there be a bad list catenation in the OC code somewhere?

**Comment by cdamken** [comment]
Closing because https://github.com/owncloud/files_texteditor/issues/222#issuecomment-373362747
