### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_texteditor#236]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Removed

`.browser()`

`.live()`

`.die()`

`.sub()`

`.andSelf()`

## Changed

`.toggle()`

`.add()`

- [ ] js/vendor/ace/src-noconflict/ace.js
- [ ] js/vendor/ace/src-noconflict/keybinding-emacs.js
- [ ] js/vendor/ace/src-noconflict/keybinding-vim.js
- [ ] js/vendor/ace/src-noconflict/mode-coldfusion.js
- [ ] js/vendor/ace/src-noconflict/mode-css.js
- [ ] js/vendor/ace/src-noconflict/mode-curly.js
- [ ] js/vendor/ace/src-noconflict/mode-django.js
- [ ] js/vendor/ace/src-noconflict/mode-ejs.js
- [ ] js/vendor/ace/src-noconflict/mode-handlebars.js
- [ ] js/vendor/ace/src-noconflict/mode-html.js
- [ ] js/vendor/ace/src-noconflict/mode-html_elixir.js
- [ ] js/vendor/ace/src-noconflict/mode-html_ruby.js
- [ ] js/vendor/ace/src-noconflict/mode-jsoniq.js
- [ ] js/vendor/ace/src-noconflict/mode-less.js
- [ ] js/vendor/ace/src-noconflict/mode-luapage.js
- [ ] js/vendor/ace/src-noconflict/mode-markdown.js
- [ ] js/vendor/ace/src-noconflict/mode-mask.js
- [ ] js/vendor/ace/src-noconflict/mode-php.js
- [ ] js/vendor/ace/src-noconflict/mode-razor.js
- [ ] js/vendor/ace/src-noconflict/mode-rhtml.js
- [ ] js/vendor/ace/src-noconflict/mode-scss.js
- [ ] js/vendor/ace/src-noconflict/mode-smarty.js
- [ ] js/vendor/ace/src-noconflict/mode-soy_template.js
- [ ] js/vendor/ace/src-noconflict/mode-svg.js
- [ ] js/vendor/ace/src-noconflict/mode-twig.js
- [ ] js/vendor/ace/src-noconflict/mode-velocity.js
- [ ] js/vendor/ace/src-noconflict/mode-xml.js
- [ ] js/vendor/ace/src-noconflict/mode-xquery.js

`.after()`

`.before()`

- [ ] js/editor.js

`.replaceWith()`

`.appendTo()`

`.insertBefore()`

- [ ] js/vendor/ace/src-noconflict/ace.js

`.insertAfter()`

`.replaceAll()`

- [ ] js/vendor/ace/src-noconflict/ext-searchbox.js

`.ajax()`

- [ ] js/editor.js

## Minor

`.trigger()`

`.click()`

`.focus()`

- [ ] js/editor.js
- [ ] js/vendor/ace/src-noconflict/ace.js
- [ ] js/vendor/ace/src-noconflict/ext-searchbox.js
- [ ] js/vendor/ace/src-noconflict/keybinding-emacs.js
- [ ] js/vendor/ace/src-noconflict/keybinding-vim.js

## Neglectable

`.data()`

- [ ] js/editor.js

`.parents()`

`.focus()`

- [ ] js/editor.js
- [ ] js/vendor/ace/src-noconflict/ace.js
- [ ] js/vendor/ace/src-noconflict/ext-searchbox.js
- [ ] js/vendor/ace/src-noconflict/keybinding-emacs.js
- [ ] js/vendor/ace/src-noconflict/keybinding-vim.js

`.attr()`

`.prop()`

**Comment by PVince81** [comment]
hmmm, that's the bundled ace text editor... seems we might need to upgrade it to a version compatible with jquery 2-3

**Comment by felixheidecke** [comment]
Works as expected. Had to update the [grep script](https://gist.github.com/felixheidecke/c32ab1b38f7091f5c5d18d4a24fd0024#file-jquery-1_9-upgrade-php-L29) because the script found more than it should have 😅
