### ISSUE TITLE
jQuery UI Upgrade

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_texteditor#244]
# jQuery UI Upgrade

See the full [upgrade 1.11. guide](https://jqueryui.com/upgrade-guide/1.11/)

See the full [upgrade 1.12. guide](https://jqueryui.com/upgrade-guide/1.12/)

## [1.11] (Core) Deprecated multiple

`.focus()`

- [ ] js/editor.js
- [ ] js/vendor/ace/src-noconflict/ace.js
- [ ] js/vendor/ace/src-noconflict/ext-searchbox.js
- [ ] js/vendor/ace/src-noconflict/keybinding-emacs.js
- [ ] js/vendor/ace/src-noconflict/keybinding-vim.js

## [1.12] (Core) Removed multiple

`.focus()`

- [ ] js/editor.js
- [ ] js/vendor/ace/src-noconflict/ace.js
- [ ] js/vendor/ace/src-noconflict/ext-searchbox.js
- [ ] js/vendor/ace/src-noconflict/keybinding-emacs.js
- [ ] js/vendor/ace/src-noconflict/keybinding-vim.js

**Comment by PVince81** [comment]
all focus usages unrelated
