### ISSUE TITLE
[For 10.1] Text Editor 2.3.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#251]
### Reason
- Set max-version to 10.1 because [core platform switches to Semver](https://github.com/owncloud/core/pull/33242): https://github.com/owncloud/files_texteditor/pull/226
- PHP 7.1 and 7.2 support: https://github.com/owncloud/files_texteditor/pull/216
- clean unused imports: https://github.com/owncloud/files_texteditor/pull/215

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch release-2.3.0
- [x] Create "2.3.0 Testplan"
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) https://github.com/owncloud/files_texteditor/issues/271

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml => https://github.com/owncloud/files_texteditor/pull/252
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) => https://github.com/owncloud/files_texteditor/pull/252
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/CTyERgXxJC5M5CA
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch => https://github.com/owncloud/files_texteditor/pull/272/

**Comment by PVince81** [comment]
@DeepDiver1975 please upload to marketplace: https://cloud.owncloud.com/index.php/s/MyLPzBwld0TNCdU

changelog here: https://github.com/owncloud/files_texteditor/blob/release-2.3.0/CHANGELOG.md#230

**Comment by DeepDiver1975** [comment]
released
