### ISSUE TITLE
opening a big file does mess up the file listing

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_texteditor#290]
try to open a big .txt file

before:

![image](https://user-images.githubusercontent.com/2425577/57374778-693ded80-71bb-11e9-91a9-4c929f87ddd7.png)

then:
![image](https://user-images.githubusercontent.com/2425577/57374805-7824a000-71bb-11e9-8fb7-077a496cff3d.png)

afterwards:
![image](https://user-images.githubusercontent.com/2425577/57374818-84106200-71bb-11e9-89c1-f97be37fe31c.png)

size and modification date are wrong

**Comment by jukkapirinen2** [comment]
related to this https://github.com/owncloud/core/issues/35080
