### ISSUE TITLE
Release TextEditor 2.3.1

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_texteditor#332]
##Reason

PR #331 adjusted the text shown for opening a file from "Edit" to "Open in Text Editor" to be consistent with files_pdfviewer and richdocuments. That gives consistency for core https://github.com/owncloud/core/pull/38132 which allows multiple file open options in the UI.

PR #333 added extra detection of codings for Chinese and Japanese character sets. That will need some manual testing from somebody who knows how to use s=those character sets and can recognise when the result is "good".

The files_texteditor change does not break anything for existing oC10.* core versions, so can be released any time.

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server)) -> #342 (compare 2.3.0 testplan #271)
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] Create github tag for `v${version}RC1` on release branch
- [ ] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date

**Comment by mmattel** [comment]
@micbar could you start the process for building a public release that is available on marketplace?

**Comment by micbar** [comment]
@mmattel the release is already on the queue.
