### ISSUE TITLE
[QA] nondescriptive action "Edit" on TXT file action chooser

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_texteditor#343]
Seen with richdocuments 2.5.0RC2 on server 10.7.0 

* create a plain text file, add some lines, save.
* click the file
![image](https://user-images.githubusercontent.com/1108546/116950464-56b0fe80-ac85-11eb-8dcb-edfdb841b64c.png)

Expected behaviour: The option should be named "Text-Editor" instead of "Edit"

Similar to owncloud/richdocuments#388 (which was about PDFs)

**Comment by JammingBen** [comment]
This was already fixed a few months ago, the release is still pending: https://github.com/owncloud/files_texteditor/issues/332

The text is "Open **in** Text Editor" though. Should we leave it like that, or change again? @pmaier1

**Comment by pmaier1** [comment]
Thanks, all good :+1:

**Comment by jnweiger** [comment]
Confirmed fixed in files_texteditor-2.3.1RC1 -- Thank you!

![image](https://user-images.githubusercontent.com/1108546/117461673-1f28a780-af4e-11eb-9f05-93a3ce36375a.png)
