### ISSUE TITLE
[QA] files with invalid name will be created

### ISSUE THREAD

**Issue by iHerrmann77** [owncloud/files_texteditor#345]
Files with ".", ".." will be created and are hidden files.

Expected: A tooltip is shown '".." is an invalid name'

![invalid_filname](https://user-images.githubusercontent.com/63246306/117423859-71070880-af21-11eb-8dca-5dfa7a646bcc.png)

**Comment by phil-davis** [comment]
`..txt` is a valid file name. `..` by itself should give an error message. There are automated acceptance test scenarios for that:
https://github.com/owncloud/files_texteditor/blob/master/tests/acceptance/features/webUITextEditor/createTextFiles.feature#L108

**Comment by jnweiger** [comment]
@phil-davis I've found the webUITextEditor tests are run e.g. in https://drone.owncloud.com/owncloud/files_texteditor/1117/16/1
Is this the correct place to look? It does all tests only with php-7.2 -- judging from the names.

**Comment by phil-davis** [comment]
@jnweiger that is the test suite that tests files_texteditor with activity app together.
https://drone.owncloud.com/owncloud/files_texteditor/1117/14/10 has the "regular" test scenarios - 17 of them.

We run acceptance tests with PHP 7.2, the oldest supported version of PHP. We could easily run them all 3 times, for PHP 7.2 7.3 and 7.4. Doing that in core and all oC10 apps would take a large amount more drone agent resources in CI.

**Comment by jnweiger** [comment]
I see your point, we need to be efficient with unmerged PRs.
But when doing a release, I am more interested in compatibility with php-7-4, as that is what we recommend to customers. Tests based on the recommendations are minimums for release approval.

**Comment by phil-davis** [comment]
> Tests based on the recommendations are minimums for release approval.

@jnweiger We can easily run CI for any version of PHP. Create an issue, maybe in https://github.com/owncloud/enterprise/ or https://github.com/owncloud/qa ? And we can all discuss what is the appropriate mix of automated testing in CI. Maybe we could just switch to running all acceptance test CI with PHP 7.4.
