### ISSUE TITLE
files_texteditor does not have a logo

### ISSUE THREAD

**Issue by mmattel** [owncloud/files_texteditor#347]
looking akward on marketstore

![image](https://user-images.githubusercontent.com/3321281/118356290-c6bc6000-b574-11eb-8ff0-3d8970a8f626.png)

**Comment by JanAckermann** [comment]
![image](https://user-images.githubusercontent.com/26169327/131349927-958187c9-4426-4daa-b4e8-bc26236bedbc.png)
