### ISSUE TITLE
files_texteditor 2.6.0 release

### ISSUE THREAD

**Issue by phil-davis** [owncloud/files_texteditor#403]
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://confluence.owncloud.com/display/OG/Releasing+Apps

### Reason

- Release needed for #401 

This release requires core 10.13. `firebase/php-jwt` is moved to core, and that will come in core 10.13.0 release.

This app can be released before that - nobody will actually be able to update it until core 10.13.0 comes out, that is fine. And it needs to be bundled with 10.13.0 release.

**Comment by jnweiger** [comment]
https://github.com/owncloud/files_texteditor/releases/download/v2.6.0/files_texteditor-2.6.0.tar.gz
