### ISSUE TITLE
Text file that cannot be converted to UTF-8 remains locked after unsuccessful editing attempt

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_texteditor#411]
Seen with 2.6.1-rc.1

With #406 we added a workaround attempt when the encoding could not be correctly detected.
In case of the error, we present a requster with an error message, and the editor does not start. OK.

![grafik](https://github.com/owncloud/files_texteditor/assets/1108546/4984c48c-fbfc-4b18-b189-8e8e94f43765)
----

when the user confirms the requester with OK, the file is locked. BAD

![grafik](https://github.com/owncloud/files_texteditor/assets/1108546/8b0eeec1-2372-4feb-a212-2adecf2ecab4)
----

Expected behaviour:
* files_texteditor should release its lock, when it returns with an error.

**Comment by pako81** [comment]
Fixed by https://github.com/owncloud/files_texteditor/pull/412
