### ISSUE TITLE
Text editor messes up with trashbin breadcrumb

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_texteditor#48]
### Steps:
1. Open file "test.txt" in text editor
2. Close the editor by clicking "Close"
3. Go to "Deleted files"

### Expected result
Breadcrumb looks fine, home icon still there.

### Actual result
Home icon was replaced by "test.txt".

### Versions
stable7 (256b5a970d9b2d87414159537f24eee57318cc84)

I believe this issue might be that the text editor is using global selectors.
If https://github.com/owncloud/files_texteditor/issues/37 isn't ready yet we might want to provide a quick fix for that specific issue.

Thanks.

@tomneedham

**Comment by tomneedham** [comment]
Fixed this in the v2 using file views and no longer playing ball games with the breadcrumb
