### ISSUE TITLE
Change title from text editor

### ISSUE THREAD

**Issue by biobeo** [owncloud/files_texteditor#49]
This problem has been forwarded from ownCloud forum:
http://forum.owncloud.org/viewtopic.php?f=29&t=24656

I have changed title in other pages. Everything is fine. But when I create a newtext.txt and double click that to edit, It came up with a page that has been titled with the file name and then - ownCloud for example if I click the newtext.txt and double click to edit this file, The title will be newtext.txt - ownCloud. So my question is simple. How could I change this now?

**Comment by tomneedham** [comment]
Version 2 stores the old title. https://github.com/owncloud/files_texteditor/pull/78
