### ISSUE TITLE
[7.0.3] Text editor not compatible with browser back button

### ISSUE THREAD

**Issue by cdamken** [owncloud/files_texteditor#50]
### expected behavior

modify a text, save and click back in browser and goes back to the files directory

### actual behavior

modify a text, save and click back in browser and stay in the editing, but path appears 2 times up.

if you press many times (back) it goes randomly to any page you had open (I still can't explain why it jumps to different pages)

In reference of : https://github.com/owncloud/core/issues/12134

@jancborchardt @LukasReschke @DeepDiver1975 @PVince81

**Comment by cdamken** [comment]
@PVince81 How about the workaround? https://github.com/owncloud/files_texteditor/issues/50#issuecomment-62929645

**Comment by DeepDiver1975** [comment]
Out of scope for OC8 -> OC8.1

**Comment by PVince81** [comment]
Prerequisite work in core: https://github.com/owncloud/core/issues/13414

**Comment by oparoz** [comment]
If you don't need IE9 compatibility, this works well
```
$(window).bind('popstate', function () {
    // Calling my close button
});`
```

**Comment by DeepDiver1975** [comment]
@oparoz mind sending a pr? Thanks a lot!

**Comment by oparoz** [comment]
Not sure as this requires knowledge of the way the app works, creation of new steps in history and new calls for the close button. Usually, the browser's back button goes back one step in its history, but some apps don't add a new step and simply modify the current URL in order to not be inserted in history...

I'll gladly help the maintainer though.

**Comment by tomneedham** [comment]
Fixed with version 2 https://github.com/owncloud/files_texteditor/pull/78 thanks @oparoz

**Comment by michaelstingl** [comment]
> Steps to reproduce
> 
> Create a folder "text file test".
> Go in the new folder "text file test".
> Create a text file "textfile.txt".
> Open the text file "textfile.txt".
> Click on the "Go back one page"-button of the browser.
> Now close the text file with the ownCloud button (on the top under your username).
> You are now a folder back and not in the folder "text file test"-folder anymore.

I can confirm: Closing text editor with browser back button keeps user in the current directory. Thanks!
