### ISSUE TITLE
Text editor freezes when trying to load non-existing shared file

### ISSUE THREAD

**Issue by rzg-kaiser** [owncloud/files_texteditor#58]
editor.js:209 $.getJSON(..., loadfile.php)

Loadfile.php returns a HTML error page ("not authenticated") with HTTP status code 500
for remote shares that no longer exist.

The callback passed to $.getJSON() only gets executed on success (see jQuery docs), so the subsequent error handling never gets called and the editor pane freezes in the browser.

Possible fix (needs work to display sensible error message):
https://gist.github.com/rzg-kaiser/0feba736bd55c32406c8

**Comment by MorrisJobke** [comment]
@tomneedham Can you have a look at this? Thanks.

**Comment by DeepDiver1975** [comment]
@rzg-kaiser can I ask you to submit your patch as pull request here on github? THX

**Comment by rzg-kaiser** [comment]
@DeepDiver1975 I just submitted pull request https://github.com/owncloud/files_texteditor/pull/59

**Comment by tomneedham** [comment]
@rzg-kaiser Please can you clarify the steps taken to reproduce this bug? I tried the following, but your patch does not fix the issue:

 - Setup two users, userA and userB
 - Create a file, fileA as userA
 - Share fileA with userB
 - Load web interface as userB
 - Without refreshing, remove the share using the share dialog as userA
 - Without refreshing, try to edit the file

Expected: Nice message
Actual: Hanging editor, however loadfile.php returns a 200 HTTP code, not a 500 code.

Maybe this is a different bug :)

**Comment by rzg-kaiser** [comment]
@tomneedham The issue are *remote* shares. My slightly modified steps to reproduce look like this:

* Setup two users, User A and User B
  * Ideally, the two users should be on different servers. However due to what I consider a different issue, mounting remote shares from your own server works as well at the moment.
* User A: Create file
* User A: Share file with User B *via link*
* User B: Open link and "add to your ownCloud" (top right corner)
* User B: Accept remote share inside your ownCloud
* User B: Open file, everything works
* User A: Delete file
* User B: Try to open file -> hanging editor

However, the more I think about it, I guess this is something that ultimately should be fixed somewhere in ownCloud core. E.g. check if remote object is available before loading any app like files_texteditor.
What would be tricky is to determine if it's a transient failure (remote server temporarily down, should probably just display an error message in files_texteditor and keep the share) or permanent (remove the share altogether). 

BTW, if we use the new server to server sharing API of ownCloud 8, at least a part of the problem disappears. If user A unshares the file, user B's server gets notified and the share immediately removed there as well. However, if user A deletes the file without unsharing it first, we have the same issue as with the link share (I guess this could be rather easily solved in ownCloud core by automatically unsharing before deletion).

**Comment by michaelstingl** [comment]
@MorrisJobke What is the status here? Could the fix from @rzg-kaiser help to solve this problem? Do you need more information?

00003116

**Comment by MorrisJobke** [comment]
@michaelstingl I will test the proposed PR soon :)

**Comment by MorrisJobke** [comment]
@michaelstingl Looks good. Needs another reviewer and then we need to backport this too.

**Comment by michaelstingl** [comment]
@MorrisJobke What is the status of the backport?

**Comment by MorrisJobke** [comment]
@michaelstingl Backport is in #77

**Comment by michaelstingl** [comment]
@MorrisJobke Thank you very much!
