### ISSUE TITLE
text editor is placed on the slide menu

### ISSUE THREAD

**Issue by eephyne** [owncloud/files_texteditor#61]
On mobile view (oc8) the text editor is placed in the auto-hide sliding menu on the left so its only viewable (and only the half of it) when you slide to the right.
![](http://imgur.com/rjgGgm3.jpg)
![](http://imgur.com/P1UTauY.jpg)

**Comment by eephyne** [comment]
I changed 
#content by #app-content 
on https://github.com/owncloud/files_texteditor/blob/c05adc4411b9ee22ca1ccca1b33ebab9dcafe9dc/js/editor.js#L204

and it seem ok so far

**Comment by tomneedham** [comment]
This is fixed with https://github.com/owncloud/files_texteditor/pull/78
