### ISSUE TITLE
No txt editor in "mobile mode"

### ISSUE THREAD

**Issue by oparoz** [owncloud/files_texteditor#62]
Owncloud 8.0.2

### Steps
1. Make your browser window narrow until the sidebar disappears
2. Click on a txt file

### Expected
I should see an editor and should be able to edit text

### Actual
Everything below the navigation bar is blank
If you widen the browser, the editor shows up at some point.

**Comment by tomneedham** [comment]
Fixed with version 2 https://github.com/owncloud/files_texteditor/pull/78

**Comment by cnolin-quatral** [comment]
@tomneedham 
I have the same issue, do you have any idea on how I could fix this on my installation? 
It would be awesome if I can fix before the release of files_texteditor version 2.
