### ISSUE TITLE
mouse cursor does not suit the text

### ISSUE THREAD

**Issue by dttpy** [owncloud/files_texteditor#64]
### Steps to reproduce
1. create text file
2. edit text file, which must have more than 2 lines, and each line has more than 3 characters, the more, the better

### Expected behaviour
The mouse cursor suit the text file. If the user want to edit some words, just move the mouse cursor to the right place with mouse or keyboard, and edit.

### Actual behaviour
Move the mouse cursor to the end of a line, it is much behind/ahead the last character.
And if user edits some words, just move the mouse cursor to the "right" place, and edit, the inserted/deleted characters don't appear in the right place, but somewhere else in the same line

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** 8.0.2 & master

**Updated from an older ownCloud or fresh install:** 8.0.0-beta2

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data8',
  'dbtype' => 'sqlite3',
  'version' => '8.0.2.0',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
  'appcodechecker' => false,


  );



```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 35.0.1

**Operating system:** ubuntu 13.10

**Comment by PVince81** [comment]
Please check if you have a monospace font installed, I believe the editor needs that to work properly.

**Comment by dttpy** [comment]
tested again in detail:
This problem happens only with firefox, and only when the system language of owncloud is set as one of the asian language (chinese, japanese, korean). And if the system is using a western language like English, German, it works properly. Language setting is under "personal -- language"

**Comment by tomneedham** [comment]
Please report these issues upstream. This app simple implements the Ace editor. https://github.com/ajaxorg/ace/issues
