### ISSUE TITLE
Text size hardcoded at 16px

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/files_texteditor#65]
16px is way too big for easy editing of files. The default font size (aka removing the explicit font size setting) is around 12px, which is suitable for all text editing tasks and works better with smaller screens such as laptops.

**Comment by deMattin** [comment]
:+1: 
Additional argument to remove this:
Style related definitions (sizes, paddings, ...) should not be set in js code if it's not mandatory.
This all should be set in css files.

**Comment by DeepDiver1975** [comment]
@Xenopathic @deMattin pull requests are welcome - Thanks a lot!

**Comment by Xenopathic** [comment]
Fixed in #78
