### ISSUE TITLE
Buttons appear in breadcrumbs after clicking in the file name

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#66]
### Steps to reproduce

1. Create a text file
2. Click in the name of the file

### Expected behaviour
Nothing happens (Just refresh perhaps)

### Actual behaviour
![screen shot 2015-04-08 at 14 10 02](https://cloud.githubusercontent.com/assets/9048796/7045033/f94a8be0-ddf9-11e4-974b-ef261997b827.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.3.0","versionstring":"8.0.3 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise version.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by SergioBertolinSG** [comment]
cc @tomneedham

**Comment by PVince81** [comment]
That's the old editor. Since 8.2 it's a popup.

Closing as obsolete.
