### ISSUE TITLE
Files_texteditor gets frozen when a user tries to open a shared file as recipient which was deleted

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/files_texteditor#71]
### Steps to reproduce

1. Create two users user1 and user2.
2. user1 shares a folder with files with user2.
3. Both users are logged in.
4. user1 deletes a file from the shared folder.
5. user2 opens the deleted file.

### Expected behaviour
Some message telling file was deleted.

### Actual behaviour
UI gets frozen.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community version.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by SergioBertolinSG** [comment]
https://github.com/owncloud/core/issues/16225
moved from core

**Comment by nickvergessen** [comment]
Still happening

Also when the file is deleted while it is being edited, it afterwards fails to save. Should it recreate the file?

**Comment by icewind1991** [comment]
Can be reproduced without sharing, just delete the file in a different tab

**Comment by icewind1991** [comment]
Fix is here: #117
