### ISSUE TITLE
Insufficient permisions error message is too wide

### ISSUE THREAD

**Issue by davitol** [owncloud/files_texteditor#76]
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Send a file to a user to another server with can edit option enabled
3. Edit the file in server B
4. Disable can edit option in server A
5. Try to save the file in server B

### Expected behaviour
The 'yellow box' should fit with error message. 

### Actual behaviour
The 'yellow box' is too wide

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox

![captura de pantalla 2015-05-25 a las 14 18 22](https://cloud.githubusercontent.com/assets/10596560/7797313/d2f52930-02ea-11e5-846d-f453feef2715.png)

**Comment by DeepDiver1975** [comment]
@davitol can you please test this without the theme? THX

**Comment by davitol** [comment]
@DeepDiver1975 same behaviour without the theme. The 'yellow box' is too wide

**Comment by tomneedham** [comment]
The new editor no longer uses the default notification style.
