### ISSUE TITLE
Text files do not save

### ISSUE THREAD

**Issue by davitol** [owncloud/files_texteditor#80]
### Steps to reproduce
1. Create a new .txt file
2. Edit it.
3. Try to save it

### Expected behaviour
The file changes should be saved

### Actual behaviour
The file does not save and the 'save button' keeps on saving status. Same behaviour in EE version.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox

**Comment by davitol** [comment]
500 Internal Server Error happens

owncloud.log -->

{"reqId":"D4058YGEf7peBr+xpnt4","remoteAddr":"82.159.139.58","app":"PHP","message":"Call to undefined function OC_L10N() at \/opt\/owncloud\/apps\/files_texteditor\/ajax\/savefile.php#31","level":3,"time":"2015-06-09T08:15:26+00:00"}

**Comment by jnfrmarks** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
@davitol while fixing another issue this should already be solved as well - please test #79 - THX

**Comment by davitol** [comment]
:+1: fixed with https://github.com/owncloud/files_texteditor/pull/79

**Comment by schiesbn** [comment]
fix merged, will be released woth oC8.1
