### ISSUE TITLE
UI defect

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/files_texteditor#90]
There is no file opening progress indicator.
In case of a slow backend it could take 10 seconds to open a file.

Please consider adding an indicator that is consistent with ownCloud's UI.
Thank you!

**Comment by szepeviktor** [comment]
For example `core/img/loading.gif`.

**Comment by tomneedham** [comment]
This is fixed in the new version https://github.com/owncloud/files_texteditor/pull/78 thanks
