### ISSUE TITLE
Text editor can't handle locked exception files

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/files_texteditor#93]
Use the steps from https://github.com/owncloud/core/issues/16569#issue-81024330 while having locking enabled and you will get an empty dialog prompt when try to open the locked file.

cc @DeepDiver1975 @PVince81 @icewind1991

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/core/pull/17811

**Comment by cmonteroluque** [comment]
@rperezb QA to check so we can close?

**Comment by rperezb** [comment]
@davitol can you please take care of this one and a smoke test of the test editor on 8.2 
thx

**Comment by davitol** [comment]
It works in oc server 8.2. beta 1. Using the steps set in owncloud/core#16569 (comment), the exception occurs. :+1:
but I don't know if this regression bug https://github.com/owncloud/files_texteditor/issues/114 is due to the fix

**Comment by MorrisJobke** [comment]
> It works in oc server 8.2. beta 1. Using the steps set in owncloud/core#16569 (comment), the conflict occurs. :+1:

Okay. Then we can close this.
